# Generated by Django 4.2 on 2023-04-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=255)),
                ('sequence_data_file', models.FileField(upload_to='sequencing/files')),
                ('quality_scores', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
            ],
        ),
    ]
