# Generated by Django 4.2 on 2023-04-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing', '0002_alter_sequence_sequence_data_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=255)),
                ('reference_file', models.FileField(upload_to='references/files')),
            ],
        ),
    ]
