# Generated by Django 4.2 on 2023-05-02 23:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing', '0003_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='reference_file',
            field=models.FileField(upload_to='references/files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='sequence_data_file',
            field=models.FileField(blank=True, upload_to='sequencing/files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
        migrations.CreateModel(
            name='AnalysisStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('result_file', models.FileField(blank=True, upload_to='sequencing/results', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequencing.reference')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequencing.sequence')),
            ],
        ),
    ]
